/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Enrollment, EnrollmentCreate } from './dtos/Enrollment.dto';
import { EnrollmentController } from './Enrollment.controller';
import { EnrollmentService } from './Enrollment.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('EnrollmentController', () => {
  let controller: EnrollmentController;
  let spyService: EnrollmentService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: EnrollmentService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [EnrollmentController],
      providers: [EnrollmentService, ApiServiceProvider],
    }).compile();

    controller = module.get<EnrollmentController>(EnrollmentController);
    spyService = module.get<EnrollmentService>(EnrollmentService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call EnrollmentController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call EnrollmentController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Enrollment();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
