/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Enrollment } from './Enrollment.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EnrollmentService } from './Enrollment.service';
import { EnrollmentController } from './Enrollment.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Enrollment])],
  providers: [EnrollmentService],
  exports: [EnrollmentService],
  controllers: [EnrollmentController],
})
export class EnrollmentModule {}
