import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class EnrollmentCreate {
  @ApiProperty()
  enrollment_date: string;
  @ApiProperty()
  status: string;
}

export class Enrollment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  enrollment_date: string;
  @ApiProperty()
  status: string;
}
